CREATE TYPE MEMBERSHIP_STATUS as ENUM('PENDING', 'APPROVED', 'DENIED');
CREATE TYPE MEMBERSHIP_TYPE as ENUM('MEMBER', 'OWNER');

CREATE TABLE "public"."Group" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "public"."GroupMembership" (
  id SERIAL PRIMARY KEY NOT NULL,
  "memberId" INTEGER NOT NULL,
  "groupId" INTEGER NOT NULL,
  "type" MEMBERSHIP_TYPE NOT NULL DEFAULT 'MEMBER',
  "status" MEMBERSHIP_STATUS NOT NULL DEFAULT 'PENDING',
  FOREIGN KEY ("memberId") REFERENCES "public"."User"(id),
  FOREIGN KEY ("groupId") REFERENCES "public"."Group"(id),
  UNIQUE("memberId", "groupId")
);