DROP DATABASE IF EXISTS "nexus_groups";
CREATE DATABASE "nexus_groups";

CREATE TYPE MEMBERSHIP_STATUS AS ENUM('PENDING', 'APPROVED', 'DENIED');
CREATE TYPE MEMBERSHIP_ROLE AS ENUM('MEMBER', 'ADMIN', 'TRADER');
CREATE TYPE PAYOUT_CURRENCY AS ENUM('BTC', 'ETH', 'LTC');

CREATE TABLE "public"."Group" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "public"."GroupMembership" (
  id SERIAL PRIMARY KEY NOT NULL,
  "memberId" INTEGER NOT NULL,
  "groupId" INTEGER NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT FALSE,
  "role" MEMBERSHIP_ROLE NOT NULL DEFAULT 'MEMBER',
  "status" MEMBERSHIP_STATUS NOT NULL DEFAULT 'PENDING',
  FOREIGN KEY ("groupId") REFERENCES "public"."Group"(id),
  UNIQUE("memberId", "groupId")
);

CREATE TABLE "public"."GroupMembershipOption" (
  id SERIAL PRIMARY KEY NOT NULL,
  "groupId" INTEGER NOT NULL,
  membershipFee NUMERIC NOT NULL,
  membershipLength INTEGER NOT NULL,
  FOREIGN KEY ("groupId") REFERENCES "public"."Group"(id)
);

ALTER TABLE "public"."Group"
  ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "public"."Group"
  ADD CONSTRAINT unique_name UNIQUE("name");

ALTER TABLE "public"."Group"
  ADD COLUMN "description" TEXT;

ALTER TABLE "public"."Group"
  ALTER COLUMN "description" SET NOT NULL;

ALTER TABLE "public"."Group"
  ADD COLUMN telegram VARCHAR(255),
  ADD COLUMN discord VARCHAR(255),
  ADD COLUMN email VARCHAR(255),
  ADD COLUMN "payoutAddress" VARCHAR(255),
  ADD COLUMN "payoutCurrency" PAYOUT_CURRENCY NOT NULL DEFAULT 'BTC',
  ADD COLUMN "payInPlatform" BOOLEAN NOT NULL DEFAULT FALSE;
